SET NOCOUNT ON;

PRINT '=== NumberSeries columns ===';
SELECT ORDINAL_POSITION, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'NumberSeries'
ORDER BY ORDINAL_POSITION;

PRINT '=== Delivery columns ===';
SELECT ORDINAL_POSITION, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Delivery'
ORDER BY ORDINAL_POSITION;

PRINT '=== Applied migrations (last 15) ===';
SELECT TOP 15 MigrationId, ProductVersion
FROM dbo.__EFMigrationsHistory
ORDER BY MigrationId DESC;
