# ============================================================================
# reset-uat-dairy-password.ps1
#
# Resets the local UAT DAIRY_MANAGER account (Hemant Sharma, UserId 36,
# branch 6 = DB0001 Dabua) to the standard dev/UAT password
# 'DoodhDirect@123' using the application's exact PBKDF2-SHA512 format.
#
#   Hash format: pbkdf2-sha512-v1$<iterations>$<saltB64>$<keyB64>
#   Iterations  : 120000 (appsettings.json -> Authentication:Identity:PasswordIterations)
#   Salt/Key    : 16 / 32 bytes, SHA-512
#
# PS 5.1 cannot compute SHA-512 PBKDF2 (Rfc2898DeriveBytes is SHA-1 only), so
# the hash is generated by the tiny .NET tool in scripts/tools/pbkdf2-gen.
#
# QUOTED_IDENTIFIER must be ON for the UPDATE (Msg 1934 otherwise) — enforced
# via sqlcmd -I and an explicit SET QUOTED_IDENTIFIER ON in the batch.
# ============================================================================

$ErrorActionPreference = "Stop"

$Password    = "DoodhDirect@123"
$ToolDir     = Join-Path $PSScriptRoot "tools\pbkdf2-gen"
$ToolProject = Join-Path $ToolDir "pbkdf2-gen.csproj"
$ToolExe     = Join-Path $ToolDir "bin\Debug\net10.0\pbkdf2-gen.exe"

# Build the hash generator on first use.
if (-not (Test-Path $ToolExe)) {
    Write-Host "Building pbkdf2-gen tool..." -ForegroundColor Cyan
    & dotnet build $ToolProject -v q
    if ($LASTEXITCODE -ne 0) { throw "Failed to build pbkdf2-gen tool." }
}

$hash = (& $ToolExe $Password | Select-Object -Last 1).Trim()
if ([string]::IsNullOrWhiteSpace($hash)) { throw "Failed to generate password hash." }

$sql = "SET QUOTED_IDENTIFIER ON; UPDATE dbo.[User] SET PasswordHash = '$hash' WHERE Id = 36 AND IsActive = 1; SELECT @@ROWCOUNT AS RowsUpdated;"

Write-Host "Generated PBKDF2-SHA512 hash for user 36 (Hemant Sharma / DAIRY_MANAGER / branch 6)."
Write-Host "Hash: $hash" -ForegroundColor DarkGray
& sqlcmd -S .\SQLEXPRESS -E -C -d DoodhDirect -I -b -Q $sql

if ($LASTEXITCODE -eq 0) {
    Write-Host "Password reset applied. Login with mobile +919354816929 / password DoodhDirect@123" -ForegroundColor Green
} else {
    Write-Host "sqlcmd failed with exit code $LASTEXITCODE" -ForegroundColor Red
    exit $LASTEXITCODE
}
